version: 0.0
Resources:
  - ContainerService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "$TASK_DEFINITION"
        LoadBalancerInfo:
          ContainerName: "$CONTAINER_NAME"
          ContainerPort: 80
# Optional properties
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets: ["$SUBNET_1","$SUBNET_2"]
            SecurityGroups: ["$SECURITY_GROUP"]
            AssignPublicIp: "ENABLED"

