version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - sudo yum install -y yum-utils shadow-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform      
      # - wget https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
      # - unzip terraform_0.15.5_linux_amd64.zip
      # - sudo mv terraform /usr/local/bin/
      - terraform --version 
  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init
  build:
    commands:
      - echo "Applying Terraform..."
      - terraform apply -auto-approve