version: 0.2

phases:
  install:
    commands:
      - yum update -y
      - yum install jq -y
      #- yum install curl -y
      # - aws ecs describe-task-definition --task-definition container_service_task_family | jq '.taskDefinition' > taskdef.json
      # - envsubst < appspec-template.yaml > appspec.yaml
  pre_build:
    commands:
      - pwd
      - ls -ltr
  build:
    commands:
      - echo Build started on `date`

  post_build:
    commands:
      - echo Running Tests..
      - |
        response_code=$(curl -s -o /dev/null -w "%{http_code}" http://$APP_URL)
        if [ $response_code -ne 200 ]; then
          echo "Test failed! Received response code $response_code"
          exit 1  # This will fail the CodeBuild stage and thus stop the pipeline.
        else
          echo "Test passed! Received response code $response_code"
        fi
      - curl -v http://$APP_URL | grep "<h2>" > test_result.html
      - cat test_result.html
artifacts:
    files: 
      - test_result.html
